// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StaffSystem.Infrastructure.Data;

#nullable disable

namespace StaffSystem.Infrastructure.Migrations
{
    [DbContext(typeof(StaffSystemDbContext))]
    partial class StaffSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StaffSystem.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company", "public");

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            CompanyName = "Головний офіс"
                        });
                });

            modelBuilder.Entity("StaffSystem.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Department", "public");

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentName = "Відділ IT"
                        },
                        new
                        {
                            DepartmentId = new Guid("d1d2d3d4-e5f6-7890-1234-567890a5b6c7"),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentName = "Відділ Маркетингу"
                        },
                        new
                        {
                            DepartmentId = new Guid("f1f2f3f4-e5f6-7890-1234-567890a8b9c0"),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentName = "Фінансовий відділ"
                        });
                });

            modelBuilder.Entity("StaffSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employee", "public");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432101"),
                            Address = "Київ, вул. Хрещатик, 15",
                            BirthDate = new DateTime(1995, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Артем",
                            HireDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Боціон",
                            MiddleName = "Миколайович",
                            Phone = "097-111-22-33",
                            PositionId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Salary = 30000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432102"),
                            Address = "Київ, бульв. Лесі Українки, 26",
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Іван",
                            HireDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Артеменко",
                            MiddleName = "Петрович",
                            Phone = "050-123-45-67",
                            PositionId = new Guid("11111111-2222-3333-4444-555555555511"),
                            Salary = 65000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432103"),
                            Address = "Київ, вул. Сагайдачного, 10",
                            BirthDate = new DateTime(1988, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("d1d2d3d4-e5f6-7890-1234-567890a5b6c7"),
                            FirstName = "Олена",
                            HireDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Михайлюк",
                            MiddleName = "Сергіївна",
                            Phone = "067-987-65-43",
                            PositionId = new Guid("22222222-2222-3333-4444-555555555522"),
                            Salary = 45000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432104"),
                            Address = "Київ, просп. Перемоги, 33",
                            BirthDate = new DateTime(1985, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("f1f2f3f4-e5f6-7890-1234-567890a8b9c0"),
                            FirstName = "Андрій",
                            HireDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Семенюк",
                            MiddleName = "Олександрович",
                            Phone = "093-222-33-44",
                            PositionId = new Guid("33333333-2222-3333-4444-555555555533"),
                            Salary = 55000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432105"),
                            Address = "Київ, вул. Ярославів Вал, 12",
                            BirthDate = new DateTime(1998, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Юлія",
                            HireDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Коваленко",
                            MiddleName = "Вікторівна",
                            Phone = "098-333-44-55",
                            PositionId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Salary = 32000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432106"),
                            Address = "Київ, вул. Костьольна, 3",
                            BirthDate = new DateTime(1992, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("d1d2d3d4-e5f6-7890-1234-567890a5b6c7"),
                            FirstName = "Тарас",
                            HireDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Шевченко",
                            MiddleName = "Григорович",
                            Phone = "066-444-55-66",
                            PositionId = new Guid("22222222-2222-3333-4444-555555555522"),
                            Salary = 48000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432107"),
                            Address = "Київ, вул. Антоновича, 70",
                            BirthDate = new DateTime(1982, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("f1f2f3f4-e5f6-7890-1234-567890a8b9c0"),
                            FirstName = "Ірина",
                            HireDate = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Бондаренко",
                            MiddleName = "Олегівна",
                            Phone = "096-555-66-77",
                            PositionId = new Guid("33333333-2222-3333-4444-555555555533"),
                            Salary = 62000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432108"),
                            Address = "Київ, вул. Жилянська, 5",
                            BirthDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Дмитро",
                            HireDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Мельник",
                            MiddleName = "Романович",
                            Phone = "063-666-77-88",
                            PositionId = new Guid("11111111-2222-3333-4444-555555555511"),
                            Salary = 70000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432109"),
                            Address = "Київ, Майдан Незалежності, 1",
                            BirthDate = new DateTime(1996, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("d1d2d3d4-e5f6-7890-1234-567890a5b6c7"),
                            FirstName = "Катерина",
                            HireDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Грищенко",
                            MiddleName = "Іванівна",
                            Phone = "095-777-88-99",
                            PositionId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Salary = 35000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432110"),
                            Address = "Київ, вул. Шовковична, 50",
                            BirthDate = new DateTime(1987, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("f1f2f3f4-e5f6-7890-1234-567890a8b9c0"),
                            FirstName = "Володимир",
                            HireDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Савчук",
                            MiddleName = "Анатолійович",
                            Phone = "099-888-99-00",
                            PositionId = new Guid("33333333-2222-3333-4444-555555555533"),
                            Salary = 58000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432111"),
                            Address = "Київ, вул. Рейтарська, 14",
                            BirthDate = new DateTime(1984, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Віталій",
                            HireDate = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Пасічник",
                            MiddleName = "Степанович",
                            Phone = "097-999-00-11",
                            PositionId = new Guid("11111111-2222-3333-4444-555555555511"),
                            Salary = 68000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432112"),
                            Address = "Київ, вул. Пушкінська, 22",
                            BirthDate = new DateTime(1999, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("d1d2d3d4-e5f6-7890-1234-567890a5b6c7"),
                            FirstName = "Світлана",
                            HireDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Лисенко",
                            MiddleName = "Василівна",
                            Phone = "050-000-11-22",
                            PositionId = new Guid("22222222-2222-3333-4444-555555555522"),
                            Salary = 42000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432113"),
                            Address = "Київ, вул. Володимирська, 56",
                            BirthDate = new DateTime(1994, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("f1f2f3f4-e5f6-7890-1234-567890a8b9c0"),
                            FirstName = "Максим",
                            HireDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Ткаченко",
                            MiddleName = "Ігорович",
                            Phone = "067-111-22-33",
                            PositionId = new Guid("33333333-2222-3333-4444-555555555533"),
                            Salary = 57000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432114"),
                            Address = "Київ, вул. Велика Васильківська, 44",
                            BirthDate = new DateTime(1997, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Ольга",
                            HireDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Мороз",
                            MiddleName = "Дмитрівна",
                            Phone = "093-222-33-44",
                            PositionId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Salary = 31000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432115"),
                            Address = "Київ, бульв. Тараса Шевченка, 11",
                            BirthDate = new DateTime(1991, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("d1d2d3d4-e5f6-7890-1234-567890a5b6c7"),
                            FirstName = "Назар",
                            HireDate = new DateTime(2021, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Зінченко",
                            MiddleName = "Богданович",
                            Phone = "098-333-44-55",
                            PositionId = new Guid("22222222-2222-3333-4444-555555555522"),
                            Salary = 50000.00m
                        },
                        new
                        {
                            EmployeeId = new Guid("e9d8c7b6-a5f4-3e2d-1c0b-9a8765432116"),
                            Address = "Київ, вул. Богдана Хмельницького, 48",
                            BirthDate = new DateTime(1989, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("b0e7a2b0-9e1d-4f8e-9c0a-3d2c1f4e6d8a"),
                            DepartmentId = new Guid("c1f4e6d8-a3d2-c1f4-e6d8-a3d2c1f4e6d8"),
                            FirstName = "Марія",
                            HireDate = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Поліщук",
                            MiddleName = "Андріївна",
                            Phone = "066-444-55-66",
                            PositionId = new Guid("11111111-2222-3333-4444-555555555511"),
                            Salary = 63000.00m
                        });
                });

            modelBuilder.Entity("StaffSystem.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PositionId");

                    b.ToTable("Position", "public");

                    b.HasData(
                        new
                        {
                            PositionId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            PositionName = "Секретар"
                        },
                        new
                        {
                            PositionId = new Guid("11111111-2222-3333-4444-555555555511"),
                            PositionName = "Провідний розробник"
                        },
                        new
                        {
                            PositionId = new Guid("22222222-2222-3333-4444-555555555522"),
                            PositionName = "Маркетолог"
                        },
                        new
                        {
                            PositionId = new Guid("33333333-2222-3333-4444-555555555533"),
                            PositionName = "Фінансовий аналітик"
                        });
                });

            modelBuilder.Entity("StaffSystem.Domain.Entities.Department", b =>
                {
                    b.HasOne("StaffSystem.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StaffSystem.Domain.Entities.Employee", b =>
                {
                    b.HasOne("StaffSystem.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffSystem.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StaffSystem.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
